title: Sitio de prueba
author: pepunker
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eleifend sem tellus, a scelerisque lacus ornare vel. In faucibus facilisis ultrices. In aliquet augue eu egestas venenatis. Ut eu lacus tincidunt tellus sodales viverra. Proin at ligula vestibulum sem pellentesque volutpat. Nulla dignissim luctus sem a aliquam. Morbi finibus pellentesque hendrerit. Maecenas tincidunt lectus non leo tempus vestibulum.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
